export const countries = [
  { label: "Buenos Aires", value: "buenos-aires" },
  { label: "Catamarca", value: "catamarca" },
  { label: "Chaco", value: "chaco" },
  { label: "Chubut", value: "chubut" },
  { label: "Córdoba", value: "cordoba" },
  { label: "Corrientes", value: "corrientes" },
  { label: "Entre Ríos", value: "entre-rios" },
  { label: "Formosa", value: "formosa" },
  { label: "Jujuy", value: "jujuy" },
  { label: "La Pampa", value: "la-pampa" },
  { label: "La Rioja", value: "la-rioja" },
  { label: "Mendoza", value: "mendoza" },
  { label: "Misiones", value: "misiones" },
  { label: "Neuquén", value: "neuquen" },
  { label: "Río Negro", value: "rio-negro" },
  { label: "Salta", value: "salta" },
  { label: "San Juan", value: "san-juan" },
  { label: "San Luis", value: "san-luis" },
  { label: "Santa Cruz", value: "santa-cruz" },
  { label: "Santa Fe", value: "santa-fe" },
  { label: "Santiago del Estero", value: "santiago-del-estero" },
  { label: "Tierra del Fuego", value: "tierra-del-fuego" },
  { label: "Tucumán", value: "tucuman" },
];


export const category = [
  { label: "Naturaleza", value: "naturaleza" },
  { label: "Deportes", value: "deportes" },
  { label: "Aire Libre", value: "aire-libre" },
  { label: "Comida", value: "comida" },
];

export const list = [
  {
    title: "Orange",
    img: "https://picsum.photos/id/10/200/300",
    price: "$5.50",
  },
  {
    title: "Orange",
    img: "https://picsum.photos/id/11/200/300",
    price: "$5.50",
  },
  {
    title: "Orange",
    img: "https://picsum.photos/id/12/200/300",
    price: "$5.50",
  },

];

export const tours = [
  {
    id: "1",
    name: "Excursión por los caminos del vino con almuerzo regional",
    guide: "Esteban Ruiz",
    location: "Mendoza",
    category: "Aire Libre",
    duration: "9 horas",
    price: "$134.011",
    rating : "5",
    description: "Por la mañana nos encontraremos con nuestro guía anfitrión, quien nos acompañará a lo largo de todo el recorrido. Posteriormente, partida hacia los caminos del vino de la región de Maipu, conocida como la cuna del Malbec, donde visitaremos dos bodegas correspondientes al circuito seleccionado, recorreremos sus instalaciones y disfrutaremos la degustación de sus vinos. Aprenderemos sobre los distintos varietales de la región, sus procesos de elaboración, así como del cuidado, crianza y fraccionamiento de los vinos mendocinos. También se incluirá amplia información sobre los sistemas de conducción de la vid y del riego. Al mediodía participaremos de un almuerzo armonizado de 3 pasos con vino de una tercera bodega. Por la tarde, regreso al hotel. Opciones de visitas a bodegas en Maipu: Achaval ferrer, Alta vista, Caelum, Tempus Alba, Carmelo patti, Casarena, Chandon, Clos de chacras, Dominio del plata, Finca decero, Kaiken, Mendel, Nieto Senetiner, Norton, Ojo de agua, Renacer, Ruca Malen, Séptima, Terraza de los andes, Pasrai, Laur y otras. Menores de 3 años gratis (no les incluye el almuerzo). Si estás pensando en qué hacer en Mendoza, esta es la solución.",
    images: [
      "https://picsum.photos/id/10/800/1200",
      "https://picsum.photos/id/11/800/1200",
      "https://picsum.photos/id/12/800/1200",
      "https://picsum.photos/id/13/800/1200",
      "https://picsum.photos/id/14/800/1200",
    ],
  },
  {
    id: "2",
    name: "Tour en Cafayate + Cachi + Humahuaca",
    location: "Cafayate",
    duration: "3 días",
    price: "$107.312",
    rating : "5",
    description: "Excursión a la Quebrada de las Conchas y Cafayate: El viaje comienza en Salta y atraviesa el Valle de Lerma, explorando formaciones rocosas únicas en la Quebrada de las Conchas, como El Anfiteatro, Garganta del Diablo y otros. Luego, en Cafayate, se visitan viñedos conocidos por su producción de Torrontés. Después del almuerzo, el regreso se hace a través de la Quebrada de las Conchas, La Garganta y el Valle de Lerma. Excursión a Cachi por el Parque Nacional los Cardones: Esta excursión lleva a los visitantes a Cachi, una hermosa ciudad en los Valles Calchaquíes. El viaje ofrece vistas espectaculares, pasando por el Parque Nacional Los Cardones y alcanzando altitudes de hasta 3,384 metros. La ciudad de Cachi ofrece la oportunidad de visitar su museo arqueológico y su iglesia antes de regresar a Salta. Día completo en Humahuaca: Este recorrido comienza en Salta y explora la impresionante Quebrada de Humahuaca, declarada Patrimonio de la Humanidad por la UNESCO. Se visitan lugares como Purmamarca, Tilcara, Huacalera, Uquía y Humahuaca. El itinerario incluye la observación de lugares emblemáticos y culturales, como el cerro de los Siete Colores, antiguas ruinas, museos y monumentos históricos. Cada excursión ofrece una experiencia única y la oportunidad de explorar la rica cultura y paisajes de la región. Estas excursiones se realizan en tres días, y el orden se coordina con el operador local. Si estás buscando qué hacer en Cafayate, estas excursiones son una excelente opción para disfrutar de la belleza y la historia de la región.",
    images: [
      "https://picsum.photos/id/15/800/1200",
      "https://picsum.photos/id/16/800/1200",
      "https://picsum.photos/id/17/800/1200",
      "https://picsum.photos/id/18/800/1200",
      "https://picsum.photos/id/19/800/1200",
    ],
  },
  {
    id: "3",
    name: "Espectáculo de tango en Teatro Astor Piazzolla",
    location: "Buenos Aires",
    duration: "2 horas y 30 minutos",
    price: "$17.417",
    rating : "5",
    description: "Vive una noche de tango en Buenos Aires. Disfruta de uno de los espectáculos de tango más representativos de la ciudad: Piazzolla Tango. La llegada al Teatro Astor Piazzola, a la Galería Güemes, es ya una invitación para que los amantes de la arquitectura tomen hermosas fotos. El edificio de diseño Art Nouveau de 1915 fue declarado Patrimonio Arquitectónico de la Ciudad de Buenos Aires.",
    images: [
      "https://picsum.photos/id/25/800/1200",
      "https://picsum.photos/id/27/800/1200",
      "https://picsum.photos/id/28/800/1200",
      "https://picsum.photos/id/29/800/1200",
      "https://picsum.photos/id/33/800/1200",
    ],
  },
  {
    id: "4",
    name: "Balcones de Calafate 4x4, Zipline o Trekking",
    location: "El Calafate",
    duration: "4 horas",
    price: "$49.849",
    rating : "5",
    description: "Ascenso en 4x4 hasta los Balcones del Cerro Huyliche para apreciar vistas panorámicas de la Cordillera de los Andes, Lago Argentino y El Calafate. 3 modalidades para el descenso (se elige una de ellas al momento de hacer la reserva): FULL 4X4, TREKKING (caminata guiada de 60 minutos aprox) o TIROLESA. Al finalizar, en la casona antigua de la estancia serviremos el almuerzo, merienda o cena.",
    images: [
      "https://picsum.photos/id/37/800/1200",
      "https://picsum.photos/id/46/800/1200",
      "https://picsum.photos/id/49/800/1200",
      "https://picsum.photos/id/54/800/1200",
      "https://picsum.photos/id/57/800/1200",
    ],
  },
  {
    id: "5",
    name: "Museu do Amanhã, AquaRio y Bulevar Olímpico",
    location: "Río de Janeiro",
    duration: "4 horas",
    price: "$28.421",
    rating : "5",
    description: "La Zona Portuaria de Río te encantará. En esta excursión, explorarás los principales atractivos del Puerto Maravilla, que atraen a turistas de todo el mundo. Ve de cerca a más de 8.000 animales en AquaRio, aprende sobre la tecnología en el Museo del Mañana y pasea por el Bulevar Olímpico, donde podrás fotografiar el mayor panel de grafitis del mundo, reconocido por el Guinness.",
    images: [
      "https://picsum.photos/id/66/800/1200",
      "https://picsum.photos/id/70/800/1200",
      "https://picsum.photos/id/71/800/1200",
      "https://picsum.photos/id/69/800/1200",
      "https://picsum.photos/id/74/800/1200",
    ],
  },
  {
    id: "6",
    name: "Visita al Parque de las Aves",
    location: "Iguazú",
    duration: "3 horas y 30 minutos",
    price: "$28.421",
    description: "Ve cientos de pájaros de cerca. En este paseo pensado para toda la familia, conocerás el mayor parque de aves de América Latina y te sorprenderás con diferentes especies, como tucanes, guacamayos y el águila más grande del mundo. Descubre la experiencia. El traslado te recogerá en tu hotel o punto de encuentro y te llevará a la segunda atracción más visitada de la ciudad. El Parque das Aves recibe más de 800 mil visitantes al año. Flamencos, loros y cormoranes de corona roja son algunas de las aves que encontrarás allí. Recorre un fácil sendero de 1,5 km en medio del exuberante Bosque Atlántico. Te sorprenderá la majestuosa postura del águila arpía, una de las aves de presa más poderosas del planeta. Qué tal si combinas este tour con una visita a las Cataratas del Iguazú? Consulta las opciones disponibles y vive una experiencia única en contacto con la naturaleza.",
    rating : "5",
    images: [
      "https://picsum.photos/id/75/800/1200",
      "https://picsum.photos/id/83/800/1200",
      "https://picsum.photos/id/100/800/1200",
      "https://picsum.photos/id/101/800/1200",
      "https://picsum.photos/id/111/800/1200",
    ],
  },
  {
    id: "7",
    name: "Aventura en la selva amazónica",
    location: "Amazonas",
    duration: "5 días",
    price: "$2,500",
    rating: "4.8",
    description: "Explora la selva amazónica y descubre su flora y fauna única en este emocionante viaje de 5 días. Incluye excursiones guiadas, alojamiento en la selva y más.",
    images: [
      "https://picsum.photos/id/120/800/1200",
      "https://picsum.photos/id/121/800/1200",
      "https://picsum.photos/id/122/800/1200",
      "https://picsum.photos/id/123/800/1200",
      "https://picsum.photos/id/124/800/1200",
    ],
  },
  {
    id: "8",
    name: "Recorrido gastronómico en Lima",
    location: "Lima",
    duration: "1 día",
    price: "$150",
    rating: "4.9",
    description: "Prueba la deliciosa comida peruana en un recorrido gastronómico por Lima. Visita los mejores restaurantes y disfruta de platos tradicionales.",
    images: [
      "https://picsum.photos/id/125/800/1200",
      "https://picsum.photos/id/126/800/1200",
      "https://picsum.photos/id/127/800/1200",
      "https://picsum.photos/id/128/800/1200",
      "https://picsum.photos/id/129/800/1200",
    ],
  },
  {
    id: "9",
    name: "Paseo en globo sobre el Valle de Colchagua",
    location: "Colchagua",
    duration: "3 horas",
    price: "$300",
    rating: "4.7",
    description: "Experimenta la emoción de un paseo en globo aerostático sobre el hermoso Valle de Colchagua. Vistas panorámicas impresionantes y desayuno incluido.",
    images: [
      "https://picsum.photos/id/130/800/1200",
      "https://picsum.photos/id/131/800/1200",
      "https://picsum.photos/id/132/800/1200",
      "https://picsum.photos/id/133/800/1200",
      "https://picsum.photos/id/134/800/1200",
    ],
  },
  {
    id: "10",
    name: "Exploración de la Ciudad Perdida",
    location: "Santa Marta",
    duration: "4 días",
    price: "$1,800",
    rating: "4.6",
    description: "Embárcate en una emocionante aventura de 4 días para descubrir la antigua Ciudad Perdida en la selva colombiana. Un viaje único en la vida.",
    images: [
      "https://picsum.photos/id/135/800/1200",
      "https://picsum.photos/id/136/800/1200",
      "https://picsum.photos/id/137/800/1200",
      "https://picsum.photos/id/138/800/1200",
      "https://picsum.photos/id/139/800/1200",
    ],
  },
  {
    id: "11",
    name: "Tour de vinos en Valle de Casablanca",
    location: "Valle de Casablanca",
    duration: "1 día",
    price: "$120",
    rating: "4.9",
    description: "Degusta vinos premium en el hermoso Valle de Casablanca. Incluye visitas a bodegas y una experiencia culinaria inolvidable.",
    images: [
      "https://picsum.photos/id/140/800/1200",
      "https://picsum.photos/id/141/800/1200",
      "https://picsum.photos/id/142/800/1200",
      "https://picsum.photos/id/143/800/1200",
      "https://picsum.photos/id/144/800/1200",
    ],
  },
  {
    id: "12",
    name: "Aventura de espeleología en cuevas de Patagonia",
    location: "Patagonia",
    duration: "2 días",
    price: "$700",
    rating: "4.8",
    description: "Explora las cuevas subterráneas de la Patagonia en una emocionante aventura de espeleología. Alojamiento y guías expertos incluidos.",
    images: [
      "https://picsum.photos/id/145/800/1200",
      "https://picsum.photos/id/146/800/1200",
      "https://picsum.photos/id/147/800/1200",
      "https://picsum.photos/id/148/800/1200",
      "https://picsum.photos/id/149/800/1200",
    ],
  },
  {
    id: "13",
    name: "Safari fotográfico en Serengeti",
    location: "Serengeti",
    duration: "7 días",
    price: "$3,500",
    rating: "4.9",
    description: "Embárcate en un safari fotográfico de 7 días en el Serengeti de Tanzania. Captura la vida silvestre en su entorno natural.",
    images: [
      "https://picsum.photos/id/1/800/1200",
      "https://picsum.photos/id/151/800/1200",
      "https://picsum.photos/id/152/800/1200",
      "https://picsum.photos/id/153/800/1200",
      "https://picsum.photos/id/154/800/1200",
    ],
  },
  {
    id: "14",
    name: "Recorrido arqueológico en Machu Picchu",
    location: "Cusco",
    duration: "2 días",
    price: "$600",
    rating: "4.9",
    description: "Descubre los misterios de Machu Picchu en un recorrido arqueológico de 2 días. Incluye guía experto y alojamiento en Aguas Calientes.",
    images: [
      "https://picsum.photos/id/155/800/1200",
      "https://picsum.photos/id/156/800/1200",
      "https://picsum.photos/id/157/800/1200",
      "https://picsum.photos/id/158/800/1200",
      "https://picsum.photos/id/159/800/1200",
    ],
  },
  {
    id: "15",
    name: "Aventura de buceo en la Gran Barrera de Coral",
    location: "Australia",
    duration: "3 días",
    price: "$1,200",
    rating: "4.7",
    description: "Explora la belleza submarina de la Gran Barrera de Coral en una emocionante aventura de buceo. Incluye alojamiento en una isla tropical.",
    images: [
      "https://picsum.photos/id/160/800/1200",
      "https://picsum.photos/id/161/800/1200",
      "https://picsum.photos/id/162/800/1200",
      "https://picsum.photos/id/163/800/1200",
      "https://picsum.photos/id/164/800/1200",
    ],
  },
  {
    id: "16",
    name: "Ruta del vino en Napa Valley",
    location: "Napa Valley",
    duration: "1 día",
    price: "$180",
    rating: "4.8",
    description: "Degusta los vinos de Napa Valley en un recorrido que incluye visitas a bodegas de renombre y una deliciosa comida gourmet.",
    images: [
      "https://picsum.photos/id/165/800/1200",
      "https://picsum.photos/id/166/800/1200",
      "https://picsum.photos/id/167/800/1200",
      "https://picsum.photos/id/168/800/1200",
      "https://picsum.photos/id/169/800/1200",
    ],
  },
  {
    id: "17",
    name: "Crucero en mar de las pompas",
    location: "Nunca Jamas",
    duration: "2 día",
    price: "$1523",
    rating: "3.8",
    description: "Ve lo mejor de mar de las pampas en un crucero como todos los demas.",
    images: [
      "https://picsum.photos/id/170/800/1200",
      "https://picsum.photos/id/171/800/1200",
      "https://picsum.photos/id/172/800/1200",
      "https://picsum.photos/id/173/800/1200",
      "https://picsum.photos/id/174/800/1200",
    ],
  },
];
